/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package protokol;

public enum Protokol {

    OPERACIJA_ULOGUJ_SE,
    OPERACIJA_REGISTRUJ_SE,
    OPERACIJA_VALIDIRAJ_KORISNICKO_IME,
    OPERACIJA_DODAJ_KOMPANIJU,
    OPERACIJA_VRATI_SVE_KOMPANIJE,
    OPERACIJA_VRATI_SVE_KOMPANIJE_PO_ID,
    OPERACIJA_DODAJ_KORISNIKA,
    OPERACIJA_VRATI_SVE_KORISNIKE,
    OPERACIJA_DODAJ_PREPARAT,
    OPERACIJA_VRATI_SVE_PREPARATE,
    OPERACIJA_VRATI_SVE_PREPARATE_PO_ID,
    OPERACIJA_DODAJ_RASPORED,
    OPERACIJA_OBRISI_RASPOREDE_TRETMANA,
    OPERACIJA_VRATI_SVE_RASPOREDE,
    OPERACIJA_DODAJ_REZERVACIJU,
    OPERACIJA_VRATI_SVE_REZERVACIJE,
    OPERACIJA_DODAJ_TRETMAN,
    OPERACIJA_IZMENI_TRETMAN,
    OPERACIJA_OBRISI_TRETMAN,
    OPERACIJA_VRATI_SVE_TRETMANE,
    OPERACIJA_VRATI_SVE_TRETMANE_PO_ID,
    OPERACIJA_OBRISI_PREPARATE_TRETMANA,
    OPERACIJA_DODAJ_PREPARATE_TRETMANA,
    OPERACIJA_VRATI_SVE_PREPARATE_TRETMANA,
    OPERACIJA_DODAJ_ZAPOSLENOG,
    OPERACIJA_VRATI_SVE_ZAPOSLENE,
    OPERACIJA_VRATI_ZAPOSLENE_PO_ID,
    OPERACIJA_DODAJ_U_SESIJU,
    OPERACIJA_DAJ_ID_KORISNIKA_IZ_SESIJE,
    OPERACIJA_STAMPAJ_PDF;
}
